import React from 'react';
import { ImageIcon } from './Icon';

interface ResultDisplayProps {
  isLoading: boolean;
  error: string | null;
  generatedImage: string | null;
  generatedText: string | null;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ isLoading, error, generatedImage, generatedText }) => {
  const Placeholder = () => (
    <div className="flex flex-col items-center justify-center text-center text-gray-500 h-full">
      <ImageIcon />
      <h3 className="mt-4 text-xl font-semibold text-gray-400">您生成的圖片將會顯示在這裡</h3>
      <p className="mt-1 text-sm">在左側配置您的設定，然後點擊「生成圖片」。</p>
    </div>
  );

  const Loader = () => (
    <div className="w-full h-full flex flex-col space-y-4">
        <div className="bg-gray-700/50 rounded-2xl animate-pulse aspect-square w-full"></div>
        <div className="h-6 bg-gray-700/50 rounded-lg animate-pulse w-3/4"></div>
        <div className="h-6 bg-gray-700/50 rounded-lg animate-pulse w-1/2"></div>
    </div>
  );
  
  const ErrorDisplay = () => (
    <div className="flex flex-col items-center justify-center text-center text-red-400 border-2 border-red-500/50 bg-red-900/20 rounded-2xl p-6 h-full">
        <p className="font-bold">生成失敗</p>
        <p className="mt-2 text-sm">{error}</p>
    </div>
  );

  return (
    <div className="bg-gray-900/50 rounded-2xl p-6 w-full h-full min-h-[500px] flex flex-col">
      {isLoading ? <Loader /> : 
        error ? <ErrorDisplay /> : 
        generatedImage ? (
          <div className="flex flex-col items-center space-y-4">
            <img 
              src={generatedImage} 
              alt="Generated by AI" 
              className="w-full max-w-full h-auto object-contain rounded-2xl shadow-2xl shadow-black/50"
            />
            {generatedText && (
                <p className="text-gray-300 text-sm bg-gray-800 p-4 rounded-lg w-full text-center">
                    {generatedText}
                </p>
            )}
          </div>
        ) : <Placeholder />
      }
    </div>
  );
};

export default ResultDisplay;